#!/usr/bin/env expect -f
set timeout 30
spawn ssh -o StrictHostKeyChecking=no root@93.127.186.217
expect "password:"
send "MISSMICHOU783450859@kwizera\r"
expect "$ "
send "echo CONNECTED_OK\r"
expect "CONNECTED_OK"
send "uname -a\r"
expect "$ "
send "ls /var/www/ 2>/dev/null\r"
expect "$ "
send "ls /home/ 2>/dev/null\r"
expect "$ "
send "ls /opt/ 2>/dev/null\r"
expect "$ "
send "find / -name '.env' -path '*/umunsi*' 2>/dev/null\r"
expect "$ "
send "find / -name 'wp-config.php' 2>/dev/null\r"
expect "$ "
send "find / -name 'settings.php' -path '*/drupal*' 2>/dev/null\r"
expect "$ "
send "find / -name 'database.yml' 2>/dev/null\r"
expect "$ "
send "find / -name 'docker-compose.yml' 2>/dev/null | head -5\r"
expect "$ "
send "psql -l 2>/dev/null || mysql -e 'SHOW DATABASES;' 2>/dev/null\r"
expect "$ "
send "exit\r"
expect eof
